name             'windows-visualstudio'
maintainer       'Opex Software'
maintainer_email 'gg@opexsoftware.com'
license          'All rights reserved'
description      'Installs .NET and then Visual Studio'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'windows'
depends          'windows'
depends          'visualstudio'
depends          'dotnetframework'
